version: '3.5'

services:
  localstack:
    image: localstack/localstack:0.11.0
    ports:
      - '4566:4566'   # LocalStack Edge
      - '8055:8080'   # LocalStack Console
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
